### ISSUE TITLE
Hotkey combinations not working, standalone hotkeys do

### ISSUE THREAD

**Issue by ghost** [robiot/XClicker#35]
### ISSUE TYPE:
 - Bug Report

#### OS / ENVIRONMENT:
 * Operating system: Void Linux x86_64
 * De or Wm: GNOME 41.5 w/ Mutter (on Xorg)
 * XClicker version: 1.3.2

#### STEPS TO REPRODUCE:
1. Set a hotkey combination (Ctrl / Shift + Something)
2. Press that hotkey combination

#### EXPECTED BEHAVIOUR:
After pressing the hotkey combination, the clicker should start.

#### ACTUAL BEHAVIOUR:
Nothing happens.

#### Additional information (optional):
Everything else pretty much works, I can set the hotkey to F8 for e.g. and after pressing that it will start. Setting the hotkey to Shift + F8, Ctrl + F8, R_Shift + F8 etc. will not work and the clicker won't start after pressing the combination.

**Comment by robiot** [comment]
Hey @czarhex. While I really appreciate your feedback, you should think about writing kindly and non offensive. I am an open-source developer. Therefore I don't get paid for my work. I try to implement as much as the users suggests, but sometimes the motivation isn't there.

Since this is an- as said before, open source project, you have all rights in the world to contribute to it if you are unhappy with a feature or two. If you don't know how to code, you can open an issue describing the enchantment instead of calling the developer a "dickhead".

Thanks


Br

**Comment by czarhex** [comment]
Sorry if I offended you, I assumed you were mocking me with the "Try that? :)"
