### ISSUE TITLE
Hotkey to start/stop

### ISSUE THREAD

**Issue by robiot** [robiot/XClicker#4]

**Comment by freakonaut** [comment]
Hey, 
im running Xclicker 1.5 and was unable to configure the start/stop hotkey, it just was not registering the keypresses.
It also is not auto clicking when a key is pressed to start the clicker.
I tried running with privileges because i'm like that, everything worked this time.  
Thats weird isn't it?

**Comment by robiot** [comment]
@freakonaut It is weird, it should work without privileges. Are you sure that you are running Xorg?

**Comment by remi-maurice** [comment]
Sorry in case you tried to dug the issue and i wasted your time @robiot , i am unable to reproduce the issue now and can't remember why and how it did that.

**Comment by robiot** [comment]
Great!
