### ISSUE TITLE
Seperate key bindings for regular hold and normal repeat options

### ISSUE THREAD

**Issue by Mrarthtato** [robiot/xclicker#59]
It would be nice to have a separate key binding for holding and normal repeat options so that one key would be a hold down autoclicker and one would be a toggle one

**Comment by robiot** [comment]
I don't personally think this option would be necessary since it's very easy to change the mode. If you want to use it like you mentioned, you can. Just open up 2 instances and configure one with hold mode and the other with normal mode.
![image](https://user-images.githubusercontent.com/68228472/176738730-7dd20fac-d5f4-4d02-800f-bd0f88272e53.png)
